### ISSUE TITLE
.jar no encuentra la main class

### ISSUE THREAD

**Issue by pablopenna** [Foo-Manroot/Time-Wanderer#1]
**$java -jar Time-Wanderer.jar** 
Error: no se ha encontrado o cargado la clase principal main.MainClass

**Comment by Foo-Manroot** [comment]
Justo acabo de probarlo en Ubuntu 16.04 con Java 1.8 y me funciona bien. 
¿En qué sistema te está dando el problema?

**Comment by pablopenna** [comment]
Pues en Ubuntu 16 con Java 1.8. Tienes el oficial o el OpenJDK? Yo estoy utilizando el oficial.

**Comment by Foo-Manroot** [comment]
También tengo la versión de Oracle
`$ java -version` produce la siguiente salida:
<pre>
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
</pre>

¿Puedes comprobar si el .jar está bien formado?
Si descomprimes el _.jar_ (`unzip Time-Wanderer.jar`) debería crearse un archivo _main/MainClass.class_

También puede ser que se haya descargado mal. Para comprobarlo, `sha1sum Time-Wanderer-dist1.0.tar.gz` devuelve **5298c8c7cc9ab8371397e81d04916f3087e75476**

Si todo está correcto, intenta añadir el directorio actual al classpath, a ver si es que no sabe dónde está: `java -classpath . -jar TimeWanderer.jar`

**Comment by pablopenna** [comment]
Ya funciona, muchas gracias. Eres un genio. He mirado el código y ojalá algún día pueda llegar a programar como usted. Si tuviera una empresa no dudaría en contratarte, dimitir y nombrarte mi sucesor. Un completo genio. Mis enhorabuenas.

P.D: Aquí tienes unos apuntes de Conocimiento y Razonamiento Automatizado, por si alguna vez en tu vida los necesitas: https://www.dropbox.com/s/apfc6x6i2jllkez/Tmeas4_5.PDF?dl=0
